version: "3.3"

networks:
  revod_regtest_network:
volumes:
  revod_regtest_volume:

services:
  charon_regtest:
    image: revo/charon:dev
    container_name: charon_regtest
    build: 
        context: ../../
        cache_from:
          - golang:1.18-alpine
    ports:
        - "23889:23889"
    environment: 
        - REVO_RPC=http://revo:testpasswd@revo_regtest:3889
        - COMPOSE_PROJECT_NAME=regtest
    volumes:
        - ../standalone/myaccounts.txt:$GOPATH/github.com/revolutionchain/charon/myaccounts.txt
        - ../../https:/https
        - ../../logs:/logs
    depends_on:
      - revo_regtest
    command: --bind 0.0.0.0 --accounts $GOPATH/github.com/revolutionchain/charon/myaccounts.txt --log-file /logs/charonLogs.txt --dev --https-key /https/key.pem --https-cert /https/cert.pem
    networks:
      - revod_regtest_network

  revo_regtest:
    ports:
      - "3889:3889"
    image: revo/revo
    container_name: revo_regtest
    command: revod -regtest -txindex -addrindex=1 -rpcbind=0.0.0.0:3889 -rpcallowip=0.0.0.0/0 -logevents -rpcuser=revo -rpcpassword=testpasswd -deprecatedrpc=accounts -printtoconsole
    volumes:
      - revod_regtest_volume:/root/.revo
    networks:
      - revod_regtest_network
