version: "3.3"
services:
  charon:
    image: revo/charon:dev
    build:
      context: ../../
      dockerfile: ./Dockerfile
      cache_from:
        - golang:3.16-alpine
        - revo/charon:dev
    ports:
      - "23889:23889"
    environment:
      - REVO_RPC=http://revo:testpasswd@revo:3889
    volumes:
      - ../../:/src:ro
    depends_on:
      - revo
    command: --bind 0.0.0.0 --accounts /src/myaccounts.txt --dev
  revo:
    ports:
      - "3889:3889"
    image: revo/revo-seeded
    build:
      context: ../../docker
      dockerfile: ./revo-seeded.Dockerfile
      cache_from:
        - revo/revo-seeded
    container_name: revo_seeded_testchain
    command: revod -regtest -addrindex -txindex -rpcbind=0.0.0.0:3889 -rpcallowip=0.0.0.0/0 -logevents -rpcuser=revo -rpcpassword=testpasswd -deprecatedrpc=accounts -printtoconsole
  openzeppelin:
    image: revo/charon-openzeppelin
    build:
      context: .
      dockerfile: ./openzeppelin.Dockerfile
      cache_from:
        - revo/charon-openzeppelin
    environment:
      - GENERATE_TO_ADDRESS=qW28njWueNpBXYWj2KDmtFG2gbLeALeHfV
    depends_on:
      - charon
    command: truffle test --network docker
